version: "3.8"
services:
  app:
    build: 
      context: .
    container_name: pickside-backend
    image: pickside-backend-image
    ports: 
      - '4000:4000'
      - '8000:8000'
    stdin_open: true
    tty: true