@baseUrlApi=http://localhost:8000
@baseUrlAuth=http://localhost:4000
@bearerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlRvbnlIYWtpbUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InRvbnkiLCJlbWFpbFZlcmlmaWVkIjpmYWxzZSwiaXNzIjoiaHR0cDovL3BpY2tzaWRlLmNvbSIsInN1YiI6IjY0MWE0OGRmYmY2NDRjODg0MjkwOTFhZiIsImlhdCI6MTY3OTQ0ODU1NywiZXhwIjoxNjc5NDQ4NjE3fQ.IIcuJzdgPGmREiz8Y_fOMZiua3pad4wSrUI47MDeTkc
@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlRvbnlIYWtpbUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InRvbnkiLCJlbWFpbFZlcmlmaWVkIjpmYWxzZSwiaXNzIjoiaHR0cDovL3BpY2tzaWRlLmNvbSIsInN1YiI6IjY0MWE0OGRmYmY2NDRjODg0MjkwOTFhZiIsImlhdCI6MTY3OTQ0ODU5MiwiZXhwIjoxNjc5NTM0OTkyfQ.VgwpK1OjFOTV_IjznICXrkTJJ9v40tQHhiZ5WGHSaMU

GET {{baseUrlApi}}/activities HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

###

POST {{baseUrlAuth}}/login HTTP/1.1
Content-Type: application/json

{
    "data": {
        "username": "tony", 
        "password": "123"
    }
}

###

GET {{baseUrlAuth}}/token HTTP/1.1
Content-Type: application/json
Authorization: BEARER {{bearerToken}}

{

}

###