GET http://localhost:3000/posts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5ODEyLCJleHAiOjE1Njg3NTk4Mjd9.0i6Im2gKz7jj8wM7aZZzOPaBS_xHoZWAqBwnldn-lQQ

###

DELETE http://localhost:4000/logout HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###

GET http://localhost:4000/token HTTP/1.1
Content-Type: application/json
Cookies: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbnkiLCJpYXQiOjE2Nzg5MzQ2MzEsImV4cCI6MTY3ODkzNDY2MX0.Yqf-f1nvJB_vhCBTiBTigeneM-jjol9YIFqWNDqB-JE
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbnkiLCJpYXQiOjE2Nzg5MzQ2MzEsImV4cCI6MTY3ODkzNDY2MX0.Yqf-f1nvJB_vhCBTiBTigeneM-jjol9YIFqWNDqB-JE

###

POST http://localhost:4000/login HTTP/1.1
Content-Type: application/json

{
    "data": {
        "username": "tony", 
        "password": "123"
    }
}